version: '2'
services:
  rabbitmq:
    environment:
      RABBITMQ_NODENAME: "rabbit"
    image: rabbitmq:3.7.8-management
    networks:
    - default
    ports:
    - "${DEV_MQ_PORT}:5672"
  mysql:
    image: mysql:5.6.41
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./_dev/mysql:/var/lib/mysql:z
    networks:
      - default
    expose:
      - "3306"
    ports:
      - "${DEV_DB_PORT}:3306"
