apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: infra-wayne
  name: infra-wayne
  namespace: default
data:
  app.conf: |-
    appname = wayne
    httpport = 8080
    runmode = prod
    autorender = false
    copyrequestbody = true
    StaticDir = public:static
    EnableDocs = true
    EnableAdmin = true
# ... add your config